name: "Network: Build and Deploy"
on:
  push:
    branches:
      - infra/actions
jobs:
  check:
    uses: "./.github/workflows/check_version.yml"
    with:
      plugin-root: "./packages/plugins/network"
      plugin-branch: "build/network"
  
  build:
    needs: [check]
    if: needs.check.outputs.has_change == 'true'
    uses: "./.github/workflows/build.yml"
    with:
      oscd_plugin_pat: ${{ secrets.PAT_REPO_OSCD_PLUGINS }}
      plugin-root: "./packages/plugins/network"
      plugin-branch: "build/network"